class_name ENUMS

enum GAME_STATE { NOT_STARTED, IN_PROGRESS, FINISHED }

enum TURN_STATE { ROLLING, SELECTING }

enum PLAYER_STATE { NEW_TURN, ROLLED, SELECTED }

enum MOVE_RESULT { NOT_SUCCESSFUL, SUCCESSFUL, FINAL }

enum PAWN_PLACE { HOME, BOARD, FINAL }

enum PLAYER_TYPE { HUMAN, AI }
